src-d/gitbase

- sql/expression.go
- sql/expression/boolean.go
- sql/expression/comparison.go
- sql/expression/expression_test.go
- sql/expression/get_field.go
- sql/expression/literal.go
- sql/plan/filter.go
- sql/plan/filter_test.go
- sql/plan/project.go
- sql/plan/project_test.go
- sql/type.go
> Use expressions in Filter and Project

- git/commits.go
- mem/table.go
- sql/core.go
- sql/expression/star.go
- sql/parse/parse.go
- sql/plan/filter.go
- sql/plan/limit.go
- sql/plan/project.go
- sql/plan/sort.go
- sql/plan/sort_test.go
- sql/plan/transform_test.go
- sql/plan/unresolved.go
* Fix Sort to use Expressions.
> add TransformExpressionsUp.

- git/commits.go
- mem/table.go
- sql/analyzer/analyzer.go
- sql/analyzer/analyzer_test.go
- sql/analyzer/rules.go
- sql/analyzer/rules_test.go
- sql/catalog.go
- sql/plan/project.go
- sql/plan/unresolved.go
- sql/plan/unresolved_test.go
* Add analyzer.Analyzer.
* Add rule to resolve table.
> add analyzer package.

- database.go
> Make database table names readable

- README.md
Fixes #137 
I removed the codebeat one until we have it. Someone with permissions needs to add the repo to codebeat (/cc @mcuadros?)
> update links and badges in README

- blobs.go
- blobs_test.go
- cmd/gitquery/server.go
- commits.go
- commits_test.go
- internal/function/is_remote.go
- internal/function/is_remote_test.go
- internal/function/is_tag.go
- internal/function/is_tag_test.go
- references.go
- references_test.go
- remotes.go
- remotes_test.go
- repositories.go
- repositories_test.go
- session.go
- tree_entries.go
- tree_entries_test.go
Depends on https://github.com/src-d/go-mysql-server/issues/36 and https://github.com/src-d/go-mysql-server/pull/87 (that's why CI fails)
> gitquery: implement session

- internal/function/commit_contains.go
- internal/function/commit_contains_test.go
- internal/function/registry.go
- session.go
Depends on #149 (which depends on more stuff)
Closes #132
> internal/function: implement commit_contains function 

- internal/function/commit_has_blob.go
- internal/function/commit_has_blob_test.go
- internal/function/registry.go
rename `commit_contains` function to `commit_has_blob` as said in #152
> internal/function: rename commit_contains to commit_has_blob

- integration_test.go
- references.go
- references_test.go
Depends on #166 
HEAD reference was not being returned in the references table.
>  gitquery: return HEAD reference on refs table

- commits.go
Just as we talked about in #169
> gitquery: add tree_hash column to commits table

- integration_test.go
Closes #155 
Also has a fix for the current test.
> it: head commits

- blobs.go
- blobs_test.go
- env.go
> gitquery: add content column to blobs table

- integration_test.go
> it: repositories per year

- integration_test.go
Closes #159 
Depends on #178 
Depends on https://github.com/src-d/go-mysql-server/pull/103
>  it: commits that appear on more than one reference

- filters.go
Along with https://github.com/src-d/go-mysql-server/pull/123, fixes master build
> gitquery: do not handle index number fix anymore

- blobs_test.go
- commits_test.go
- database_test.go
- integration_test.go
- references_test.go
- remotes_test.go
- repositories_test.go
- repository_pool.go
- repository_pool_test.go
- tree_entries_test.go
> Store a list of paths instead of instantiated reposititories

- Makefile
> Fix error on Makefile

- internal/function/commit_has_blob.go
- internal/function/commit_has_blob_test.go
- internal/function/commit_has_tree.go
- internal/function/commit_has_tree_test.go
Closes #191 
Before:
```
BenchmarkCommitHasTree/commit_has_tree-4                    3000            519234 ns/op          297322 B/op       1276 allocs/op
PASS
ok      github.com/src-d/gitquery/internal/function     2.154s
```
After:
```
BenchmarkCommitHasTree/commit_has_tree-4                 1000000              1036 ns/op             240 B/op          7 allocs/op
PASS
ok      github.com/src-d/gitquery/internal/function     1.593s
```
Before:
```
BenchmarkCommitHasBlob/commit_has_blob-4                     500           2605190 ns/op         1143268 B/op       1768 allocs/op
PASS
ok      github.com/src-d/gitquery/internal/function     2.105s
```
After:
```
BenchmarkCommitHasBlob/commit_has_blob-4                 1000000              1013 ns/op             240 B/op          7 allocs/op …
```
> perf: add caches to commit_has_blob and commit_has_tree

- .travis.yml
- Dockerfile
Closes #203 
Publishing with CI will be done on another PR.
Final image is not alpine because we're using cgo and I could not get it to work in any way. If someone knows how to run CGO binaries on alpine, please come forward.
> add dockerfile

- .gitignore
> just ignore binaries if you build locally

- iterator.go
> gitbase: skip hash references that do not point to commits

- Gopkg.lock
- cmd/gitbase/main.go
- cmd/gitbase/server.go
- cmd/gitbase/version.go
- iterator.go
- references.go
- repository_pool.go
- session.go
> *: add logging

- integration_test.go
- iterator.go
- references.go
>  gitbase: ignore missing HEAD references

- cmd/gitbase/server.go
> Make repo directories optional for server cmd

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/src-d/go-mysql-server.v0/.gitignore
- vendor/gopkg.in/src-d/go-mysql-server.v0/Gopkg.lock
- vendor/gopkg.in/src-d/go-mysql-server.v0/engine_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/rules.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/rules_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/alias.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/arithmetic.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/arithmetic_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/between.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/boolean.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/common.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/aggregation/avg.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/aggregation/count.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/aggregation/max.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/aggregation/min.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/arraylength.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/isbinary.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/substring.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/time.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/literal.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/logic.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/star.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/unresolved.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/type.go
> vendor: upgrade go-mysql-server to get dual table fix

- cmd/gitbase/server.go
It allows defining multiple git folders or siva folders.
> cmd: server, support multiple siva and git folders

- README.md
- cmd/gitbase/server.go
- internal/function/commit_has_blob.go
- internal/function/commit_has_tree.go
- internal/function/history_idx.go
- iterator.go
- iterator_test.go
- repository_pool.go
- repository_pool_test.go
- session.go
> Add env var to skip go-git errors

- LICENSE
- README.md
> license: relicense to Apache 2.0

- integration_test.go
- internal/function/uast.go
- internal/function/uast_test.go
> internal/function: make UAST be able to use language results

- cmd/gitbase/command/server.go
> cmd/gitbase: glob support for adding repositories

- integration_test.go
- internal/rule/squashjoins.go
- internal/rule/squashjoins_test.go
- squash_iterator.go
- squash_iterator_test.go
Depends on #271 
Closes #268 
Closes #263 
Closes #264
>  *: add squashes for joining repos with commits, entries and blobs 

- commit_blobs.go
- commit_blobs_test.go
- commits.go
- common_test.go
- database.go
- database_test.go
Closes #273 
Depends on @erizocosmico 's PR #280
> gitbase: implement commit_blobs table

- blobs.go
- database.go
- database_test.go
- files.go
- files_test.go
- filters.go
- integration_test.go
- references.go
- squash_iterator.go
- tree_entries.go
>  gitbase: implement files table with pushdown 

- README.md
Closes #286 
Only merge this after all the new tables are added.
> readme: updated README to reflect current schema

- DCO
> Add DCO file

- README.md
Updates #303
Signed-off-by: Francesc Campoy <campoy@golang.org>
> avoid compiling code before dependencies are ready

- cmd/gitbase/command/server.go
updates #303 
Signed-off-by: Francesc Campoy <campoy@golang.org>
> make it clear that the server is now running

- README.md
Closes #306 
Depends on https://github.com/src-d/go-mysql-server/pull/226
> *: add a comment in the README pointing to the supported SQL subset

- commit_blobs.go
- commit_blobs_test.go
- commit_files.go
- commit_files_test.go
- commit_trees.go
- database.go
- database_test.go
- files.go
- integration_test.go
- internal/rule/squashjoins.go
- internal/rule/squashjoins_test.go
- ref_commits.go
- repository_pool_test.go
- session.go
- squash_iterator.go
Implements `commit_files` table with squash and indexes.
> *: implement commit_files table

- cmd/gitbase/command/server.go
- cmd/gitbase/main.go
- docs/using-gitbase/configuration.md
> cmd/gitbase: make squash rule active by default

- docs/using-gitbase/examples.md
Closes #352 
Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>
> docs: add create index examples

- integration_test.go
- internal/rule/squashjoins.go
- internal/rule/squashjoins_test.go
> internal/rule: fix indexes of filters in squash

- rev-upgrade.sh
> fix script for osx/linux

- docs/using-gitbase/configuration.md
Add the new GITBASE_READONLY env var to the docs.
> Add GITBASE_READONLY to docs

- internal/function/uast.go
- internal/function/uast_test.go
> internal/function: don't fail if the uast function can't parse a blob

- Makefile
command `make mysql-upgrade` upgrades mysql to the latest (master) revision
> mysql-upgrade target

- docs/using-gitbase/indexes.md
Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>
> docs: add indexes section

- docs/using-gitbase/examples.md
> Documentation: Add more examples

- docs/README.md
> Add indexes section into the summary.

- cmd/gitbase/command/server.go
- cmd/gitbase/command/version.go
- cmd/gitbase/main.go
> cmd/gitbase: fix version and build info

- squash_iterator.go
- squash_iterator_test.go
Closes https://github.com/src-d/go-mysql-server/issues/292
> gitbase: make squash iterators cancellable

- docs/using-gitbase/getting-started.md
> docs: add troubleshoothing info about connecting with mysql client 8.x

- Gopkg.lock
- Gopkg.toml
- integration_test.go
- internal/rule/squashjoins.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/resolve_natural_joins.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/resolve_natural_joins_test.go
Fixes #388 
This PR fix partially the bug. The other part of the fix is in https://github.com/src-d/go-mysql-server/pull/296.
When that PR in go-mysql-server is merged, I'll update the dependency in this PR and then the CI should pass the tests I added.
> internal/rule: fix projections when squash joins

- session.go
- session_test.go
> gitbase: add a more descriptive error connecting to bblfsh

- docs/using-gitbase/examples.md
- docs/using-gitbase/schema.md
- ref_commits.go
> *: rename ref_commits index to history_index

- cmd/gitbase/command/server.go
- repository_pool.go
Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>
> *: add siva files to the repository pool with an ID

- references.go
- squash_iterator.go
> gitbase: do not warn on not found HEAD

- _testdata/regression.yml
- cmd/gitbase/main.go
- regression_test.go
I'd like to add a file with regression queries. `regression-gitbase` will look into this file. If file doesn't exist (e.g. because of old version of gitbase) it will be tested against the default set of queries (like it worked before).
> Regression queries

- README.md
- docs/using-gitbase/getting-started.md
Fixes https://github.com/src-d/gitbase/issues/433
Signed-off-by: Anna Tsolakou <tsolakou.a@gmail.com>
> Text improvement - documentation

- _testdata/regression.yml
- cmd/gitbase/command/server.go
- integration_test.go
- regression_test.go
> parse and analyze regression queries

- docs/using-gitbase/getting-started.md
Signed-off-by: Anna Tsolakou <tsolakou.a@gmail.com>
> Organise installation steps

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/fsobject.go
- vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/packfile.go
- vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/dotgit.go
- vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go
Fix some performance improvements added on the last version.
> Update go-git to latest version

- docs/using-gitbase/examples.md
Closes #447 
Added examples for all the UAST UDFs, including those in #446 #449.
> docs/using-gitbase: add UAST UDFs examples

- docs/using-gitbase/getting-started.md
> docs: make some snippets copyable

- README.md
People get confused and think that it is already working https://github.com/src-d/datasets/issues/77#issuecomment-420935678
> Change the notice about Spark integration

- docs/using-gitbase/getting-started.md
> docs: fix how to install oniguruma on linux

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-syntax.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/engine_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/concat.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/set.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go
>  Update go-mysql-server dependency

- internal/function/uast.go
When execution is parallel only one `uastFunc` is used. This makes its hash to be used by more than one worker at the same time and producing panics.
A better way to solve this is having one `uastFunc` per worker instead of only one.
> function: fix race condition getting UASTs

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/src-d/go-git.v4/plumbing/cache/buffer_lru.go
- vendor/gopkg.in/src-d/go-git.v4/plumbing/cache/buffer_test.go
- vendor/gopkg.in/src-d/go-git.v4/plumbing/cache/object_lru.go
- vendor/gopkg.in/src-d/go-git.v4/plumbing/cache/object_test.go
- vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go
- vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object_test.go
Also adds a fix for LRU cache size.
> vendor: upgrade go-git, fix closed file in pack iter

- references.go
- squash_iterator.go
> gitbase: remove warnings on symbolic references

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-syntax.md
- internal/rule/squashjoins_test.go
- session.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/engine.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/engine_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/server/context.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/server/handler.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/server/handler_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/parallelize.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/parallelize_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/process.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/process_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/rules.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/drop_index.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/drop_index_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/processlist_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/processlist.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/processlist_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/session_test.go
> vendor: upgrade go-mysql-server

- cmd/gitbase/command/server.go
- internal/function/uast.go
- internal/function/uast_test.go
- internal/function/uast_utils.go
- session.go
> *: remove old uast serialization option

- .travis.yml
- integration_test.go
- internal/function/uast.go
> internal/function: fix uast_extract returned type

- docs/using-gitbase/functions.md
> docs: explain how uast and uast_mode functions serilize data

- .gitignore
- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-syntax.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/README.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/resolve_columns.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/resolve_columns_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/set.go
Fixes: https://github.com/src-d/gitbase/issues/510
> Upgrade mysql

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-syntax.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/engine_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/resolve_columns.go
Closes https://github.com/src-d/gitbase/issues/500
> Upgrade mysql with fix #500

- Dockerfile
- Makefile
> Dockerfile: add gitbase version to the binary

- docs/using-gitbase/examples.md
- docs/using-gitbase/functions.md
> docs: improve uast functions documentation

- internal/rule/squashjoins.go
- internal/rule/squashjoins_test.go
> rule: fix unability to check conditions of natural joins

- docs/using-gitbase/getting-started.md
> docs: fix optional dependencies

- docs/using-gitbase/functions.md
> docs: add code example on how to manage serialized uast data

- docs/README.md
- docs/using-gitbase/optimize-queries.md
> docs: guide on how to optimize queries

- docs/using-gitbase/getting-started.md
Signed-off-by: Maartje Eyskens <maartje@eyskens.me>
> Add instructions how to run in docker with bblfsh

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-syntax.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/process.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/index.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/insert.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/process.go
Fix https://github.com/src-d/gitbase/issues/563
> Upgrade go-mysql-server to v0.1.0

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-syntax.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/driver.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/lookup.go
> Fix indexes upgrading go-mysql-server dependency

- docs/README.md
- docs/using-gitbase/supported-clients.md
> docs: add supported clients

- docs/using-gitbase/examples.md
Added `repository_id`s to `JOIN .. ON` clauses and unified the indentation to four spaces (which was used before).
This would hopefully close #575.
> Added repository_ids in non-natural joins in the examples

- cmd/gitbase/command/server.go
Closes: https://github.com/src-d/go-mysql-server/issues/488
> Set default db name (gitbase)

- Dockerfile
- Makefile
Hey there,
i saw that your Dockerfile depended on Debian. I refactored it to depend on Alpine which is much smaller. This should not change anything functional, it just decreases the image size
> Refactored Dockerfile

- .travis.yml
Documentation for `docker-push-latest-release`:
https://github.com/src-d/ci/tree/v1#docker-build-and-push
Fixes: #501
> travis: use docker-push-latest-release from ci

- docs/using-gitbase/examples.md
> docs: add example of how to use show processlist

- internal/function/uast.go
- internal/function/uast_test.go
Partially closes: https://github.com/src-d/gitbase/issues/616
> Fix uast_extract panic.

- docs/using-gitbase/indexes.md
> Update an index note about good practice for bitmaps.

- docs/using-gitbase/optimize-queries.md
> docs: add explanation about using explain to assess performance issues

- internal/function/uast.go
- internal/function/uast_utils.go
> add warns to session on uast functions

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-clients.md
- docs/using-gitbase/supported-syntax.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/server/handler.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/comparison.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/soundex.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/like.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/parse/lock.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/resolved_table.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/processlist.go
> Update go-mysql-server dependency

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-clients.md
- docs/using-gitbase/supported-syntax.md
- integration_test.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/optimization_rules.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/registry.go
- vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/time.go
Fixes https://github.com/src-d/gitbase/issues/651
This PR upgrades `go-mysql-server` to the latest version.
Also, one new integration test (NATURAL JOINS in a subquery) is added.
> Fix natural join panic for subqueries

- _testdata/regression.yml
Related to https://github.com/src-d/regression-gitbase/issues/6
> make query-id two-digit number.

- .travis.yml
- Dockerfile
> ci: fix versions of docker image binary

- .travis.yml
- Makefile
- e2e/e2e_test.go
> add e2e tests against the built binary

- cmd/gitbase/main.go
- commit_files.go
- commits.go
- filters.go
- index.go
- integration_test.go
- internal/rule/squashjoins.go
- internal/rule/squashjoins_test.go
- packfiles.go
- repository_pool.go
- squash_iterator_test.go
- tools/rev-upgrade/main.go
> fix errors pointed out by staticcheck

- checksum.go
- checksum_test.go
> fix checksum on siva files and make consistent checksums

- commit_files.go
- commit_files_test.go
Fixes https://github.com/src-d/gitbase/issues/673
Any good ideas how to test it?
> Set index for commitFilesRowIter.

- commit_files_test.go
- filters.go
- filters_test.go
- integration_test.go
Fixes https://github.com/src-d/gitbase/issues/683
I kept selectors (so far so good), just removed `unfold` for `Or` expressions.
> Fix OR filtering on different columns.

- Gopkg.lock
- Gopkg.toml
- docs/using-gitbase/functions.md
- docs/using-gitbase/indexes.md
- docs/using-gitbase/supported-clients.md
- docs/using-gitbase/supported-syntax.md
- vendor/gopkg.in/src-d/go-mysql-server.v0/server/handler.go
> Update go-mysql-server to make kill query works properly

- .gitignore
> remove gitbase binary

- Gopkg.toml
> Add go-oniguruma to Gopkg.toml 

- .travis.yml
Attempt to fix https://github.com/src-d/gitbase/issues/778
> Fix order of make commands

- integration_test.go
- internal/rule/squashjoins.go
- internal/rule/squashjoins_test.go
> rule: fix squash rule with convert_dates

- integration_test.go
- ref_commits.go
- remotes.go
- squash_iterator.go
> avoid panic when there are no fetch URLs in remote config

- pull_request_template.md
> Add checks on PRs

- docs/using-gitbase/functions.md
> docs: add is_vendor to functions

- CHANGELOG.md
> Prepare release v0.21.0-beta1

- CHANGELOG.md
- docs/using-gitbase/functions.md
- internal/function/commit_stats.go
- internal/function/commit_stats_test.go
Fixes #859 
Fixes #860 
Depends on: #863
> improve commit stats

- CHANGELOG.md
- go.mod
- go.sum
> Switch gocloc to version v0.3.0

- CHANGELOG.md
> Prepare v0.21.0-beta2 release

- CHANGELOG.md
- docs/using-gitbase/optimize-queries.md
- internal/rule/squashjoins.go
- internal/rule/squashjoins_test.go
- squash_iterator.go
- squash_iterator_test.go
> rule: make commit_files squashable with blobs

- Dockerfile
- Makefile
> Fix container build

- go.mod
- go.sum
- partition.go
- squash_iterator_test.go
> gitbase: fix squash_iterator tests and skip partition errors

- docs/using-gitbase/examples.md
- docs/using-gitbase/functions.md
Closes #884
Closes #885
- Adds documentation for version function along with the returned format.
- Adds examples for COMMIT_STATS and COMMIT_FILE_STATS.
- Adds section about how to use COMMIT_STATS and COMMIT_FILE_STATS and
their output shape.
> docs: improve documentation of COMMIT_STATS and COMMIT_FILE_STATS

- CHANGELOG.md
- docs/using-gitbase/functions.md
- go.mod
- go.sum
> Prepare new release

- CHANGELOG.md
- go.mod
- go.sum
> Update go-mysql-server version

- CHANGELOG.md
- commit_files_test.go
- files.go
- files_test.go
- go.sum
- repository_pool_test.go
This may have been what was causing the test failures in gsc.
> fix files table by removing git log usage

- internal/function/commit_file_stats.go
- internal/function/commit_file_stats_test.go
> Fix commit_file_stats function

- docs/using-gitbase/examples.md
Fixes #936 
I removed the import paths example because we can no longer extract the import paths just using XPath. Now imports can have two forms (in Go at least):
- A single `uast:Identifier` from which you can extract the name
- A single `uast:QualifiedIdentifier` which has multiple `uast:Identifier` to extract the names from
The issue is you get something like `["bufio", "github.com", "src-d", "go-mysql-server"]` instead of `["bufio", "github.com/src-d/go-mysql-server"]` as we did before. The current output is useless for the user, so I thought it would be better to hide that from the docs until we implement something more convenient.
There are helpers to extract import paths from a node. We could implement something in gitbase to use those helpers. Perhaps some special `@imports` or …
> docs: update examples

- .travis.yml
> upgrade to go 1.12 on travis

- CHANGELOG.md
> Prepare for the new release v0.24.0-beta2

- .travis.yml
- Dockerfile
> use goproxy

- Jenkinsfile
Updated `regression-gitbase` container version and added optiomn to store output to prometheus
> Jenkinsfile -> tweaks to enable prometheus support

- docs/using-gitbase/configuration.md
- docs/using-gitbase/functions.md
- docs/using-gitbase/supported-clients.md
- go.mod
- go.sum
> Upgrade go-mysql-server version

- CHANGELOG.md
> Prepare for v0.24.0-rc1 release

- CHANGELOG.md
- go.mod
- go.sum
> Update go-mysql-server and prepare changelog for the next rc version

- CHANGELOG.md
- docs/using-gitbase/examples.md
- go.sum
- internal/function/blame.go
- internal/function/blame_test.go
Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>
> [blame] Remove redundant commit hash from results

- CODEOWNERS
- MAINTAINERS
> Change MAINTAINERS and added CODEOWNERS

- docs/using-gitbase/examples.md
> Fix documentation example.

- docs/using-gitbase/functions.md
> Add uast_imports function to documentation.

- go.mod
- go.sum
contains:
1) non-recursive iterators
2) race conditions fix https://github.com/src-d/go-borges/pull/89
> update go-borges dependency

- Jenkinsfile
> update regression-gitbase version

- CHANGELOG.md
> prepare for release 0.24.0-rc3

- Jenkinsfile
> add jenkins slack notifications
