engine_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go

Expressions for children nodes were never resolved.

sql/analyzer: fix analysis of expressions.

---

.travis.yml

When a tag will created, a new binary will be generated and uploaded to github releases section

travis: Add deploy section to create releases using tags

---

engine_test.go
sql/parse/parse.go
sql/parse/parse_test.go

* Sort was being generated after Project,
so it was not possible to ORDER BY
by a field not included in SELECT.

sql/parse: generate sort before project.

---

git/blobs.go
git/blobs_test.go
git/commits.go
git/commits_test.go
git/database.go
git/database_test.go
git/references.go
git/references_test.go
git/tags.go
git/tags_test.go
git/tree_entries.go
git/tree_entries_test.go
mem/database.go
mem/database_test.go
sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/analyzer/rules_test.go
sql/catalog.go
sql/core.go
sql/database.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/transform_test.go
sql/plan/unresolved.go
sql/plan/unresolved_test.go

PhysicalRelation is now Table, this is shorter, readable and more
understandeable for most people.

rename *relation to *table.

---

cmd/gitql/query.go
sql/analyzer/analyzer_test.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/project.go
sql/plan/project_test.go

* Add alias parsing support.
* Fix plan.Project so that it calculates schema properly
when child schema differs in names.

sql/parse: add support for expression aliases.

---

sql/analyzer/analyzer_test.go
sql/analyzer/rules.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/cross_join.go
sql/plan/cross_join_test.go

* added support to parse CROSS JOIN.
* improved CROSS JOIN code.
* added tests for CROSS JOIN with one empty side.
* added tests for CROSS JOIN parsing and analysis.

sql: support parsing and executing CROSS JOIN

---

README.md
engine.go
engine_test.go
sql/analyzer/rules.go
sql/catalog.go
sql/catalog_test.go
sql/core.go
sql/expression/aggregation.go
sql/expression/aggregation_test.go
sql/expression/common.go
sql/expression/unresolved.go
sql/parse/parse.go
sql/parse/parse_test.go
sql/plan/common.go
sql/plan/filter.go
sql/plan/group_by.go
sql/plan/group_by_test.go
sql/plan/limit.go
sql/plan/project.go
sql/plan/sort.go

* sql: add AggregationExpression interface.
* sql: add function registry to Catalog.
* sql/expression: add Count and First implementations.
* sql/plan: add GroupBy node.

sql: add GROUP BY support. Closes #52.

---

sql/parse/parse.go

* update to latest sqlparser api.
* use gitql/vitess fork instead of youtube/vitess.

sql/parse: update sqlparser api. Fixes #90.

---

cmd/gitql/query.go
internal/format/common.go
internal/format/common_test.go
internal/format/csv.go
internal/format/csv_test.go
internal/format/json.go
internal/format/json_test.go
internal/format/pretty.go
internal/format/pretty_test.go

Now you can change the output format to 2 new ones: json and csv.
- Added json support
- Added csv support
- Now the table output format is called 'pretty'. It is the default format.

cmd: added new output formats

---

cmd/gitql/shell.go

Using this library we have history out of the box.

cmd: Use readline library.

---

cmd/gitql/shell.go

Added some colors to the interactive shell, specially message errors.

cmd: add colors to shell

---

git/blobs.go
git/commits.go
git/objects.go
git/references.go
git/tags.go
git/tree_entries.go
mem/table_test.go
sql/plan/cross_join_test.go
sql/plan/describe.go
sql/plan/describe_test.go
sql/plan/filter_test.go
sql/plan/group_by.go
sql/plan/group_by_test.go
sql/plan/limit_test.go
sql/plan/project.go
sql/plan/project_test.go
sql/plan/sort_test.go
sql/plan/transform_test.go
sql/type.go

A Field would mean a cell in a row, but our previous
Field type is actually a column definition in a schema,
so Column is a more previse name.

sql: rename Field to Column.

---

sql/type.go

Native converts a value of Type into a driver.Value.
This is required for compatibility with the database/sql API.

sql: add Native value to Type.

---

cmd/gitql/query.go
cmd/gitql/query_base.go
cmd/gitql/shell.go
git/blobs.go
git/blobs_test.go
git/commits.go
git/commits_test.go
git/database.go
git/database_test.go
git/objects.go
git/objects_test.go
git/references.go
git/references_test.go
git/tags.go
git/tags_test.go
git/tree_entries.go
git/tree_entries_test.go

* now opening a non-existing repository is an error, but
it is possible to open an existing, empty repository.

update go-git api

---

blobs.go
commits.go
internal/format/pretty.go
internal/format/pretty_test.go
objects.go
references.go
references_test.go
tags.go
tree_entries.go

* adapt to latest sqle.v0 api (NULL support)
* use NULL for target/hash in references table
* cmd: in pretty printing, print strings quoted
to distinguish NULL and "NULL"
This PR depends on https://github.com/sqle/sqle/pull/25

update to latest sqle.v0 api (NULL support)

---

.travis.yml
commits.go
database_test.go

Do small changes to be able to use the last go-git v4 version.

Upgrade to latest go-git version.

---

references.go

go-git changed its API on August 2nd with commit 171b3a73e7ab7015f9eb8e98965e36dfb8ea9599. This change fixes that.

Fixes API changes from go-git

---

references.go
references_test.go

Fixes #130
From the doc:
> All the references will be resolved to a commit. If the reference is not pointing to a commit, it will not be on the table.
Schema:
* repository_id: not null, string
* name: not null, string
* hash: not null, string

Modify references table to match the document

---

.travis.yml

Requires @mcuadros or @ajnavarro to add a `GITHUB_TOKEN` environment variable to the travis configuration.

ci: upload binaries on release

---

blobs.go
blobs_test.go
commits.go
commits_test.go
common_test.go
filters.go
filters_test.go
integration_test.go
references.go
references_test.go
remotes.go
remotes_test.go
repositories.go
repositories_test.go
session.go
tree_entries.go
tree_entries_test.go

Closes #153 
This PR implements filter pushdown for all git tables, drastically reducing the amount of data we push to the joins by applying some of the filters directly inside the tables.
The filters are split in two categories:
- Regular filters: any expression that references any field in the table that requires the concrete value of the row to be executed (e.g. comparison operators, negation, udfs, ...)
- Selectors: filters that are of the form `FIELD = LITERAL`, `FIELD = LITERAL1 OR FIELD = LITERAL2 OR FIELD = LITERALN` or `FIELD IN (LIT1, LIT2, ...)` (when it's implemented) that give us a set of concrete values to directly access those rows instead of iterating over all the data. Example: `SELECT * FROM commits WHERE hash = 'foo'` we'd only go and get the commit with the hash `foo` …

gitquery: implement filter pushdown for git tables 

---

internal/function/commit_has_tree.go
internal/function/commit_has_tree_test.go
internal/function/registry.go

Closes #152 
Note that another, perhaps simpler, solution would be to add a `tree` column to the `commits` table (since the tree hash is in the commit object) and then just `commits.tree = tree_entries.tree_hash`

internal/function: add commit_has_tree UDF

---

integration_test.go

Closes #158 
Depends on #178 
Tests will fail until there is a fix on go-mysql-server for what @jfontan is working on right now.

it: commits per committer, per month and repo on a year

---

internal/function/history_idx.go

There are cases where it can enter a cycle

history_idx: do not visit a parent more than once

---

Gopkg.lock
internal/function/history_idx.go
internal/function/history_idx_test.go
vendor/github.com/hashicorp/golang-lru/.gitignore
vendor/github.com/hashicorp/golang-lru/2q.go
vendor/github.com/hashicorp/golang-lru/2q_test.go
vendor/github.com/hashicorp/golang-lru/LICENSE
vendor/github.com/hashicorp/golang-lru/README.md
vendor/github.com/hashicorp/golang-lru/arc.go
vendor/github.com/hashicorp/golang-lru/arc_test.go
vendor/github.com/hashicorp/golang-lru/doc.go
vendor/github.com/hashicorp/golang-lru/lru.go
vendor/github.com/hashicorp/golang-lru/lru_test.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru_test.go

Fixes #190 
This commit adds a LRU cache to the history_idx function, caching the indexes in which a commit is from another in the history.
Before:
```
BenchmarkHistoryIdx/history_idx-4                   2000            789749 ns/op          415896 B/op       1519 allocs/op
PASS
ok      github.com/src-d/gitquery/internal/function     2.189s
```
After:
```
BenchmarkHistoryIdx/history_idx-4                1000000              1063 ns/op             256 B/op          9 allocs/op
PASS
ok      github.com/src-d/gitquery/internal/function     1.607s
```
**DISCLAIMER:** benchmark here is biased because the same commits keep being asked again and again. In a regular production query the improvement would likely be much lower than it is here. Still an improvement, nonetheless.

internal/function: add cache for history_idx

---

Makefile
README.md

Clarifies in the README how to install the dependencies and adds a new rule to be able to build them without having to go into the vendor directory.

gitbase: build bblfsh dependencies

---

.gitignore
integration_test.go
internal/rule/squashjoins.go
internal/rule/squashjoins_test.go
iterator.go
iterator_test.go
remotes.go
remotes_test.go

This commit implements a test suite to ensure results using the squash optimization are the exact same as the ones not using it.
It also fixes two of these differences:
- Without squashing, remote iterator did not return a string but another type for the refspecs.
- Joining blobs with refs or commits could lead to extra rows because blobs could appear more than once per commit or ref. Now they only appear once.

*: tests for squash vs no squash correctness

---

repository_pool.go
repository_pool_test.go

Catch errors creating new iteratos in rowReaders

---

commits.go
commits_test.go
internal/rule/squashjoins_test.go

A new attribute `parents` has been added to the `commits` table containing an array with each commit's parent hashes.
```
MySQL [(none)]> DESCRIBE TABLE commits;
+------+------+
| name | type |
+------+------+
| hash | TEXT |
| author_name | TEXT |
| author_email | TEXT |
| author_when | TIMESTAMP |
| committer_name | TEXT |
| committer_email | TEXT |
| committer_when | TIMESTAMP |
| message | TEXT |
| tree_hash | TEXT |
| parents | JSON |
+------+------+
10 rows in set (0.00 sec)
```
```
MySQL [(none)]> select hash,committer_name,parents from commits where array_length(parents) > 1 limit 10;
+------+----------------+---------+
| hash | committer_name | parents |
+------+----------------+---------+
| c1a24566f4a89001ade1441dfbd7d98a2bd93ba8 | R.J.V. Bertin  | …
```

Expose commit parents attribute in commit table

---

README.md
cli/gitbase/cmd/server.go
cli/gitbase/main.go

Closes #249 
Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>

Rename env var GITBASE_UNSTABLE_SQUASH_ENABLE

---

README.md
blobs.go
blobs_test.go
commits.go
commits_test.go
integration_test.go
internal/function/uast.go
internal/rule/squashjoins.go
internal/rule/squashjoins_test.go
iterator.go
iterator_test.go
references.go
remotes.go
repositories.go
tree_entries.go
tree_entries_test.go

Closes #265 
Closes #266 
Closes #267 
This PR just renames the columns and adds the new ones for all tables to make the current things work. In a subsequent PR I will add the new iterators and matching possibilities, since now a lot more squashes can be done.
Partially solves #268, #264, #263

*: rename columns for easier natural joins, add repository_id

---

blobs.go
commit_blobs.go
commit_blobs_test.go
commit_trees.go
commits.go
common_test.go
filters.go
index.go
index_test.go
integration_test.go
ref_commits.go
references.go
remotes.go
remotes_test.go
repositories.go
repository_pool.go
repository_pool_test.go
squash_iterator.go
table.go
tree_entries.go

Depends on [src-d/go-mysql-server] PRs:
- https://github.com/src-d/go-mysql-server/pull/181, until this is merged, the `go-mysql-server` dependency can't be updated because of tests failing. Also here is implemented the method `IndexOf` for the schema which is used by the `IndexKeyValueIter` method
- https://github.com/src-d/go-mysql-server/pull/206, until this is merged, the `go-mysql-server` dependency can't be updated because of tests failing.
- https://github.com/src-d/go-mysql-server/pull/193, in this PR `sql.Context` is added to the `sql.Indexable` interfaces. This change is needed to have access to the repository pool from the `sql.Indexable` methods implementation.
@src-d/data-retrieval just have a look to the proposed implementation, if all is ok I'll address the dependency …

*: implement indexable interfaces on basic and relation tables

---

.travis.yml
blobs.go
commits.go
files.go
index.go
index_test.go
integration_test.go
packfiles.go
remotes.go
tree_entries.go

This PR adds support for unpacked objects, which made the index contain different objects and not match the result of the query without indexes.
A bunch of integration tests for indexes of all tables testing they output the exact same thing as the same query without indexes have been added as well.
Because it's super important to ensure the index is closed so it can be released, each index iterator has now a call to `closeIndexOnError`, which closes the index if there is an error or EOF in an iterator, ensure it's *always* closed.
After this is merged, `feature/indexable` is ready to be PR'd and merged to master.

gitbase: support for unpacked objects, integration tests added

---

Gopkg.lock
Gopkg.toml
integration_test.go
packfiles.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/analyzer.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/rules.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/rules_test.go

Depends on #308 and https://github.com/src-d/go-mysql-server/pull/218/files
Results:
```
go test -run='^$' -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: github.com/src-d/gitbase
BenchmarkQueries/simple_query/base-4                 500           2725531 ns/op          570099 B/op       3405 allocs/op
BenchmarkQueries/simple_query/indexes-4              500           2383330 ns/op          570077 B/op       3404 allocs/op
BenchmarkQueries/simple_query/squash-4              1000           1217884 ns/op          252379 B/op       1526 allocs/op
BenchmarkQueries/select_by_specific_id/base-4                100          13601108 ns/op         2815530 B/op      18485 allocs/op
BenchmarkQueries/select_by_specific_id/indexes-4              30          44128295 ns/op         2296652 B/op …
```

 gitbase: update benchmarks with indexes 

---

README.md
cmd/gitbase/command/server.go

Closes #315
Gitbase wasn't connecting to the pilosa container properly.
I made the pilosa endpoint configurable through and environment variable too to make easier run gitbase with docker.
Now it's documented too in the README.

Set pilosa endpoint through an environment variable.

---

.travis.yml

Closes #328 
Since our codebase does not have anything that is os-dependant on the darwin build I'm just building the binary just to know that it can be built in macOS with no problems.
Right now, you can't really start a docker container inside a macOS build, so there is no way we can run bblfsh there and we would need to reduce the number of tests we run for macOS quite a bit using the `-short` hack, which is kind of a pointless effort.

travis: build and upload macOS releases

---

integration_test.go
internal/rule/squashjoins.go

Fixes #322 
The bug came because the projects nodes over inner joins weren't squashed, so they stayed chained and pointing to wrong field indexes after the table squashing
```
GroupBy
├─ Aggregate(COUNT(1), refs.repository_id)
├─ Grouping(refs.repository_id)
└─ Project(refs.repository_id, refs.commit_hash, refs.ref_name, commits.commit_author_name, commits.commit_author_email, commits.commit_author_when, commits.committer_name, commits.committer_email, commits.committer_when, commits.commit_message, commits.tree_hash, commits.commit_parents, commit_blobs.blob_hash)
└─ Project(refs.repository_id, refs.commit_hash, refs.ref_name, commits.commit_author_name, commits.commit_author_email, commits.commit_author_when, commits.committer_name, commits.committer_email, commits.committer_when, …
```

internal/rule: fix squashjoins rule to squash projections properly too

---

Gopkg.lock
Gopkg.toml
docs/using-gitbase/functions.md
docs/using-gitbase/supported-syntax.md
integration_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/SUPPORTED.md
vendor/gopkg.in/src-d/go-mysql-server.v0/engine_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/rules.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/rules_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/aggregation/sum.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/aggregation/sum_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/registry.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/driver.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/driver_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/index.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/index_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/mapping.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/mapping_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/parse/parse_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/create_index_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/drop_index.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/group_by.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/sort.go
vendor/gopkg.in/src-d/go-mysql-server.v0/test/mem_tracer.go

Update go-mysql-server with all fixes that have recently been merged.

vendor: upgrade go-mysql-server

---

tree_entries.go

Closes #355 
After a lot of debugging, it turns out it was this little tiny stupid thing 😞 
I found another error while storing the index (not querying) of the tree_entries table, but I think that has something to do with go-git and not gitbase in particular.

gitbase: fix tree entry index iteration when object is unpacked

---

blobs.go
blobs_test.go
commit_blobs.go
commit_blobs_test.go
commit_files.go
commit_files_test.go
commit_trees.go
commit_trees_test.go
commits.go
commits_test.go
files.go
files_test.go
index.go
index_test.go
ref_commits.go
ref_commits_test.go
references.go
references_test.go
remotes.go
remotes_test.go
repositories.go
repositories_test.go
squash_iterator.go
tree_entries.go
tree_entries_test.go

By using custom encoder and decoder for the index keys, as opposed to golang `gob` we can save a lot of space.
This implements our own way of encoding and decoding those index keys by just writing bytes for each thing.
- For string values we write first the size (int64 in binary) and then the string itself.
- For hashes we just write 40 bytes.
- For int64 we write the number in binary.
- For bools we write 0 or 1.
Since some objects can be unpacked and not in the packfile, there are cases where the key has an offset of -1 and a hash instead or an offset >= 0 and empty hash.
Because now we're in control, instead of saving both the hash and the offset we store a bool and just one of them, potentially saving some space. Also, since this is not using reflection it should also be way faster …

gitbase: custom encode and decode of index keys to save space

---

Gopkg.lock
Gopkg.toml
cmd/gitbase/command/server.go
docs/using-gitbase/functions.md

Closes #326 
Depends on https://github.com/src-d/go-mysql-server/pull/251, so build will fail until go-mysql-server is upgraded to that

cmd/gitbase: add readonly flag

---

path_utils.go

gitbase: ignore .DS_Store files in darwin

---

files.go
fs_error_test.go
repository_pool.go

Adds tests with errors in the git repositories.
* Add new type of repo `initializedRepo` that holds a `git.Repository`
* Creates a pool with three repos:
* Repo with error reading packfile
* Repo with missing index file and ghost packfile
* Correct repo
* Two fixes dealing with errors
I don't really like the new `initializedRepo` type so I'm working on storing an interface in the pool instead of a struct with types and implementing `gitRepo`, `sivaRepo` and `initializedRepo` with the specific code. This will be done in another PR.

Test filesystem errors

---

blobs.go
commit_files.go
commits.go
files.go
fs_error_test.go
packfiles.go
packfiles_test.go
repositories_test.go
repository_pool.go
repository_pool_test.go
squash_iterator_test.go
tree_entries.go

Also add `billyRepo` for billy filesystems.
I'm not totally happy with the naming of `repository` interface as there's already a `Repository` structure and all the `gitRepository`/`gitRepo` for struct and constructor. Suggestions welcome.

gitbase/repository_pool: change repository to be an interface

---

cmd/gitbase/command/server.go
docs/using-gitbase/configuration.md

Fixes #392 
It overlaps with help, which has higher priority, so it's effectively unusable.

cmd/gitbase: remove -h flag as shortcut for --host

---

cmd/gitbase/main.go

Related to https://github.com/src-d/gitbase/issues/387
On the latest master of Githbase f12563a96d2b80eb46c476222dd77a704ed6cd10
```
$ make packages
$ ./build/gitbase_darwin_amd64/gitbase version
gitbase (undefined) - build undefined
```
This PR fixes a typo in a previous work #389, where [`const`](https://github.com/src-d/gitbase/pull/389/commits/ecde5d738537dedc0d31ecf1df39d456abf0c5b4#diff-540338d1dca7c27f738d3dd59357ca7eR12) need to be a `var`, according to the [documentation](https://golang.org/cmd/link/).
Not sure if it's worth adding a test to CI to check for this.

Fix gitbase version command

---

internal/function/uast.go

Partial fix for #403 
I've opened an issue in bblfsh client-go about the panic, so when it's fixed there the permanent fix will be on gitbase after an upgrade.
For now, I think we should guard the uast functions with recovers just in case, since bblfsh seems to be the most common source of panics and returning an error instead.

internal/function: recover from panics in uast functions

---

packfiles.go

The change forces decoder to compare repos by `ID` (not by `Path`). Thanks to this change `objectDecoder.decode` method doesn't have to create a new `RepoObjectDecoder` every time, but it re-uses internal cache.
It makes _full-scan_ queries for indexed columns much faster. For instance for 620 rows duration dropped from 14 sec. to 86 ms.
Closes: https://github.com/src-d/go-mysql-server/issues/324

Compare repos by ID.

---

squash_iterator.go
squash_iterator_test.go

Fixes #417 
Also fixes a problem with some siva files having the same fetch refspec for N remote URLs.

gitbase: do not skip repo when it has no head in squash

---

.gitignore
cmd/gitbase/main.go

We can handle `-g` option for backward compatibility with previous versions.
`-g` is not documented, but we can use it as a alias for `-d` option, e.g.:
`./gitbase server -g /tmp/boo -d /tmp/repos/ -i /tmp/indexes`.
It's done to let run regression tests with `regression-gitbase` (which by default uses `-g`)

Add -g option for backward compatibility

---

docs/using-gitbase/functions.md
internal/function/registry.go
internal/function/uast.go
internal/function/uast_test.go

This new UDF will be used to extract information from the uast nodes. The idea is pass a key identifying the information you want retrieve from a list of uast nodes and you will get back a list of values for each node in the list. For example:
```
MySQL [(none)]> select file_path,language(file_path) as lang, uast_extract(uast_xpath(uast_mode('annotated', blob_content, language(file_path)), '//*[@roleValue]'), "@type") as value_type from files where lang='Go' limit 1;
+-------------------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

internal/function: add uast_extract udf

---

Gopkg.lock
Gopkg.toml
docs/using-gitbase/configuration.md
internal/function/language.go
vendor/github.com/hashicorp/golang-lru/.gitignore
vendor/github.com/hashicorp/golang-lru/2q.go
vendor/github.com/hashicorp/golang-lru/2q_test.go
vendor/github.com/hashicorp/golang-lru/LICENSE
vendor/github.com/hashicorp/golang-lru/README.md
vendor/github.com/hashicorp/golang-lru/arc.go
vendor/github.com/hashicorp/golang-lru/arc_test.go
vendor/github.com/hashicorp/golang-lru/doc.go
vendor/github.com/hashicorp/golang-lru/go.mod
vendor/github.com/hashicorp/golang-lru/lru.go
vendor/github.com/hashicorp/golang-lru/lru_test.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru_test.go

Closes #442 
This adds a two queue lru cache to language UDF. Why a 2Q cache instead of a regular LRU? Because we do not only want the most recent but the most frequent as well to maximize the cache usage.
Since running enry on a file_path only is just marginally slower than using the cache, I decided to not use the cache unless the blob_content is being provided (we could use two caches, though) to not pollute the cache and use it only for the really expensive operations: reading stuff from blobs.
Note that the cache is per gitbase instance.
Results are pretty much the ones @ajnavarro describes in the issue.
Before:
```
mysql> select count(*) from (select file_path, language(file_path, blob_content) as language FROM files WHERE language(file_path, blob_content) = 'Go') t;
+----------+
| …
```

internal/function: use cache for expensive language operations 

---

Gopkg.lock
docs/using-gitbase/configuration.md
internal/function/uast.go
internal/function/uast_test.go
internal/function/uast_utils.go

This PR adds ~~two caches~~ one cache for the functions `uast` and  `uast_mode`. 
The main cache is set at server level, so it is shared by all the queries. It's caching UASTs requested to bblfsh
~~Meanwhile, the second cache is used at query level and it caches the parsed errors from bblfsh. I thought it makes sense in the context of the same query, that if bblfsh returns a parsed error for a blob, most probably it will return the same error for that blob during the execution of the that query.~~
Results of theses changes running this query
> select file_path,uast(blob_content,language(file_path)) from files limit 100000;
on  a set of 20 siva-files with cache sizes of `10000` are:
- `12 min 43.18 sec` -> NO CACHE
- `4 min 13.12 sec` -> CACHE
- ~~`12 min 30.88 sec` -> NO CACHE~~
- ~~`3 …

internal/function: add LRU cache for uast and uast_mode functions

---

files.go
files_test.go

Closes #473 
Projections weren't pushdowned in the `files` table. This table needs to get the column `blob_content` pushdowned to read the blobs' content, that's why this column was returning nothing.

*: pushdown projections properly in the files table

---

blobs.go
commit_blobs.go
commit_files.go
commit_trees.go
commits.go
files.go
partition.go
ref_commits.go
references.go
remotes.go
repositories.go
squash.go
table.go
tree_entries.go

Closes #477 
Since `Partitions` and `PartitionCount` is always the same for all tables, just moved them into a `partitioned` helper which can be embedded to avoid having so much repeated code.

gitbase: implement sql.PartitionCounter in all tables

---

docs/using-gitbase/configuration.md

docs: add GITBASE_CACHESIZE_MB to the documentation

---

.travis.yml

Version tag has to match `v0.1.2`

build: only tag latest in docker when version is not prerelease

---

.travis.yml

Build with go 1.11 and remove tip build to use less resources

---

docs/using-gitbase/functions.md

fixing typo in using-gitbase functions.md

---

README.md

According to [this](https://english.stackexchange.com/a/409933) comment, it's preferred to write "on a large scale" rather than "at a large scale". "at large scale" is a grammatical error.

Fixed a grammatical error

---

cmd/gitbase/command/server.go

This makes queries work again. It was using `information_schema` as the current database. It uses the first one added if not specified.

server: make gitbase the current database

---

internal/function/uast.go
internal/function/uast_test.go
internal/function/uast_utils.go

Fixes #444 
I have been trying for a while but I can't seem to reproduce the original error (which is normal, considering it's a bblfsh error and there be dragons).
Anyway, as said in the issue, the UDF should not fail, so now all errors are logged but not returned and nil is returned instead.

function: log bblfsh errors on UAST instead of returning them

---

blobs.go
commit_blobs.go
commit_files.go
commit_trees.go
commits.go
files.go
ref_commits.go
references.go
remotes.go
repositories.go
table.go
table_test.go
tree_entries.go

Fixes #647 
Turns out it was just implemented for squashed tables

gitbase: show pushed down properties to tables in explain

---

.circleci/config.yml

This adds the CircleCI setup we used to test. This is meant to keep running in parallel to Travis CI to get better results to compare the two CI solutions. See https://github.com/src-d/infrastructure/issues/209#issuecomment-444156635
cc @smola @mcuadros

Add a circleci setup to run in parallel to travis

---

cmd/gitbase/command/server.go
docs/using-gitbase/configuration.md

You can disable errors setting the log level to `fatal`.
Fixes #677

Set log level

---

_testdata/regression.yml

Add more regression queries

---

Makefile

This is causing the following error on `make dependencies` after bblfsh sdk update:
```
11:50 $ make dependencies
cd vendor/gopkg.in/bblfsh/client-go.v3 && make dependencies
make[1]: Entering directory 'work/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v3'
go get -v -t -t ./...
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v3/cmd/bblfsh-cli
cmd/bblfsh-cli/main.go:92:30: cannot use ast (type "github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v2/uast/nodes".Node) as type "gopkg.in/bblfsh/sdk.v2/uast/nodes".Node in argument to uastyml.Marshal:
"github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v2/uast/nodes".Node does not implement "gopkg.in/bblfsh/sdk.v2/uast/nodes".Node (wrong type for Clone method)
have Clone() …
```

Remove custom bblfsh build

---

Jenkinsfile

This adds a `nodeSelector` for Jenkins, as it inherits from perfomance it doesn't use the one set in the settings.

Add a nodeSelector tag for Jenkins on k8s

---

cmd/gitbase/command/server.go
cmd/gitbase/command/server_test.go

Fixes #718
When a child of one of the paths given to the gitbase server is not
readable because of permissions, the repo finding process just
stopped and no repository was added to the pool.
This skips a directory if there are no permissions to read it, so
the process can continue adding repositories to the pool as usual.

command: skip a directory if gitbase has no permission to read it

---

.travis.yml
Dockerfile
Makefile

Add oniguruma bindings into generated gitbase binary

---

commits.go

Fixes #769
git.Log was being passed as commit iter to the index iterator, but
the new commitIter should be passed instead. That generated a
discrepancy between the results of indexes and the sames queries
with no indexes.

gitbase: remove git.Log from index commit iterator

---

commit_trees.go
partition.go
ref_commits.go
references.go
repositories.go
squash_iterator.go
tree_entries.go

We have a cascade of iterators. Some iterators are not closing (what breaks a chain).
In this PR I tried to close all possible iterators. Rest of the stuff has to be done in mysql. For some cases (where we pass iterator to tables or to builders) I have a feeling that we never have a chance to close it because either it's wrapped by many interfaced or there is no right place where we can do it.
At least those simple `Close` statements  can partly fix https://github.com/src-d/gitbase/issues/765

Close iterators

---

commits.go
integration_test.go
ref_commits.go
references.go
squash_iterator.go

Fixes #745
On all iterators where references are used only hash references
are used. But we're not taking into account that hash references
can point to any kind of object, not only commit objects, which
are the only objects we care about for the references table.
This fix was already applied on the new commits iterator that
walks the history skipping unreachable commits, but it was not
consistent with the rest of the iterators, which only check if the
reference was a hash reference or not. Now this behavior is
consistent in all iterators.
`isIgnoredReference` function has been added to abstract all this
logic away so if we ever need to change the logic of this we will
only have to replace it in one place instead of being scattered
all over the codebase.
Signed-off-by: Miguel Molina …

skip references pointing to objects that are not commits

---

Makefile
e2e/e2e_test.go

makefile: fix adding version in generated binaries

---

Jenkinsfile

This PR allows to execute jenkins regression tests with smaller
repositories than the used on master branch.

Run regression tests with complexity 0 on PRs

---

commits.go
integration_test.go
ref_commits.go
references.go
squash_iterator.go

Fixes #775
Fixes #777
Before, each time we got a new reference, we were checking if it
pointed to a commit. This incurred in a performance penalty and
an increase of 2x in memory usage and 4x in allocations, as more
objects were being read from the repository.
Instead, now we use the already present resolveCommit to check it
the moment we get the object, since we have to get it anyway.
This way, we have the exact same behaviour without having any
performance penalty or memory usage increase.

perf: improve the way we check if refs are not pointing to commits

---

Gopkg.lock
Gopkg.toml
Makefile
docs/using-gitbase/functions.md
docs/using-gitbase/indexes.md
docs/using-gitbase/supported-clients.md
docs/using-gitbase/supported-syntax.md
integration_test.go
vendor/gopkg.in/src-d/go-mysql-server.v0/internal/regex/regex_go.go
vendor/gopkg.in/src-d/go-mysql-server.v0/internal/regex/regex_oniguruma.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/assign_indexes.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/analyzer/pushdown.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/expression/function/aggregation/count.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/index/pilosa/driver.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/cross_join.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/exchange.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/innerjoin.go
vendor/gopkg.in/src-d/go-mysql-server.v0/sql/plan/process.go

This PR upgrades mysql dependency. New mysql-server contains the second part of closed iterators fix and makes go regex as a default engine.
At the same time (having go regex as a default) it closes https://github.com/src-d/gitbase/issues/778

Upgrade mysql

---

Makefile

Add GO_BUILD_ARGS to static-build command

---

Makefile

Right now, we are compiling into a container. Doing this Makefile.main
is not getting correct VERSION env var because we don't have TRAVIS_TAG
in the container.
To avoid this problem, we are setting always our VERSION when `make
static-build` is called.

Set correct version on static-build

---

commits_test.go
common_test.go
references_test.go
remotes.go
remotes_test.go

Fixes https://github.com/src-d/gitbase/issues/788
For remotes with more than 1 URL, `remotesIndexKeyValueIter` skip repos.

Don't skip repos for remotes table with more than 1 URL

---

Gopkg.lock
docs/using-gitbase/examples.md
docs/using-gitbase/functions.md
internal/function/loc.go
internal/function/loc_test.go
internal/function/registry.go
vendor/github.com/hhatto/gocloc/.gitignore
vendor/github.com/hhatto/gocloc/.goreleaser.yml
vendor/github.com/hhatto/gocloc/.travis.yml
vendor/github.com/hhatto/gocloc/Gopkg.toml
vendor/github.com/hhatto/gocloc/Makefile
vendor/github.com/hhatto/gocloc/README.md
vendor/github.com/hhatto/gocloc/bspool.go
vendor/github.com/hhatto/gocloc/examples/files.go
vendor/github.com/hhatto/gocloc/examples/languages.go
vendor/github.com/hhatto/gocloc/file.go
vendor/github.com/hhatto/gocloc/file_test.go
vendor/github.com/hhatto/gocloc/gocloc.go
vendor/github.com/hhatto/gocloc/json.go
vendor/github.com/hhatto/gocloc/language.go
vendor/github.com/hhatto/gocloc/language_test.go
vendor/github.com/hhatto/gocloc/option.go
vendor/github.com/hhatto/gocloc/utils.go
vendor/github.com/hhatto/gocloc/utils_test.go
vendor/github.com/hhatto/gocloc/xml.go

This PR introduces the `https://github.com/hhatto/gocloc` through a new LOC function returning a JSON struct.
```sql
SELECT    
LANGUAGE(file_path, blob_content) as lang,     
SUM(JSON_EXTRACT(LOC(file_path, blob_content), '$.Code')) as code,  
SUM(JSON_EXTRACT(LOC(file_path, blob_content), '$.Comments')) as comments,     
SUM(JSON_EXTRACT(LOC(file_path, blob_content), '$.Blanks')) as blanks,    
COUNT(1) as files 
FROM commit_files 
NATURAL JOIN refs 
NATURAL JOIN blobs 
WHERE ref_name='HEAD' 
GROUP BY lang;
```
```
+------+------+----------+--------+-------+
| lang | code | comments | blanks | files |
+------+------+----------+--------+-------+
| Markdown | 63763 |        0 |  24316 |   693 |
| YAML | 6033 |       91 |    788 |   229 |
| Text |    0 |        0 |      0 |   437 |
| Go …
```

 function: LOC function implementation

---

cmd/gitbase/command/server.go
cmd/gitbase/command/server_test.go
path_utils.go
path_utils_test.go

Fixes #681
Still can have collisions, but reduces the probability of having them.

cmd/server/commands: use relative path as id instead of last part

---

integration_test.go
internal/function/is_vendor.go
internal/function/is_vendor_test.go
internal/function/registry.go

Fixes #823 
Note that `.gitignore` is being reported as vendor, but it's not. Bug report here: https://github.com/src-d/enry/issues/229

function: implement is_vendor function

---

.travis.yml
CHANGELOG.md
_testdata/regression.yml
docs/using-gitbase/getting-started.md
go.mod
go.sum
integration_test.go
session.go
session_test.go

- Add aliases to supportedLanguages slice to check also alias names.
- Make IsSupported to check lang names in lower case.
- Update go-mysql-server to fix some nil handling errors.
- Fix regression query that was using DISTINCT on aggregations giving
wrong results.

Fix aliases usage on bblfsh client impl.

---

cmd/gitbase/command/server.go

Uses the same log message as before except that instead of `path` it's `id`.

cli: log repositories found on startup

---

CHANGELOG.md
cmd/gitbase/command/server.go
cmd/gitbase/command/server_test.go
common_test.go
database_test.go
integration_test.go
internal/function/commit_stats_test.go
internal/function/uast_test.go
internal/rule/squashjoins_test.go
repositories_test.go
repository_pool.go
repository_pool_test.go

Also fix a bug getting the cache size from cli.
Before integrating the use of `go-borges` repositories were managed by `RepositoryPool`. When it was created it initialized a git object cache that is used by all the repositories. This cache is also used when using indexes and reading directly from packfiles (cache is retrieved with `Repository.Cache()`, https://github.com/src-d/gitbase/blob/master/packfiles.go#L239).
Now `go-borges` takes care of repository libraries and retrieving go-git repositories from them. To make it work the same we initialize `go-borges` library with a cache generated in `gitbase` (`command.Server`) but I forgot that `RepositoryPool` was also generating a cache internally and returning it when calling `Repository.Cache()`. This means that there was two different …

gitbase: use only one cache for all repositories

---

CHANGELOG.md
go.mod
go.sum

Prepare new v0.22.0 release

---

CHANGELOG.md

Prepare for v0.24.0-beta1 release

---

CHANGELOG.md
cmd/gitbase/command/server.go
docs/using-gitbase/configuration.md
init.sh

fix #934
- docker entrypoint should not force the usage of 'verbose' mode
- docker entrypoint uses 'debug' log level as default if not defined (for backward compatibility)
- verbose flag will override any other passed log level, not only 'info'
TODO;
n/a
- I added or updated examples if applicable.
- I checked that changes on schema are reflected into the documentation, if applicable.
- I updated go-mysql-server using `make upgrade` command if applicable.

Let the user define LOG_LEVEL=info using docker

---

docs/using-gitbase/functions.md
internal/function/loc.go
internal/function/loc_test.go

internal/function: use custom fixed struct as LOC result

---

.travis.yml

Removes all the installing we did for oniguruma that's now not required nor needed in the build.

cleanup unused things from travis build script

---

docs/using-gitbase/examples.md
docs/using-gitbase/functions.md
docs/using-gitbase/indexes.md
docs/using-gitbase/optimize-queries.md
docs/using-gitbase/schema.md
docs/using-gitbase/supported-languages.md

I've been reading gitbase documentation to get used to the project and the codebase, so I fixed the typos and errors I found.
Changes:
- Fix a malformed query in examples.md. It used the non-existing `commit_blob` column where it should use `blob_hash`.
- Make description of functions consistent throughout all the tables in functions.md. I decided to stick to the lower-case present-tense style, as each row is easily read as `Function X returns Y`. This is opinionated (consistency should be not), so I'm ok discussing the best style and changing it again once we agree on one.
- Fix several typos.
(Not adding the PR template here because this only updates typos in documentation, so none of the items apply here)

Fix documentation typos and make style more consistent

---

CHANGELOG.md
docs/using-gitbase/examples.md
go.mod
go.sum
internal/function/registry.go
internal/function/uast.go
internal/function/uast_test.go

Closes #943
After changes to the structure of imports, the way we used to collect
them is no longer valid, so now we're using the uast.AllImportPaths
helper included in the bblfsh sdk to obtain import paths from nodes.

function: implement uast_imports UDF

---

CHANGELOG.md

Prepare CHANGELOG for release

---

internal/function/language.go
internal/function/loc.go
internal/function/uast.go
internal/function/uast_utils.go

function: use new caches from go-mysql-server

---

Jenkinsfile

currently issue https://github.com/src-d/gitbase/issues/955 forces pipeline to fail and jenkins plot is not built
this PR replaces stages so plot should be displayed before test has failed
also related to https://github.com/src-d/regression-gitbase/issues/25

jenkinsfile -> change pipeline sequence

---

CHANGELOG.md
internal/function/blame.go

Fixes #966 
Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

Don't abort on git.Blame errors

---

CHANGELOG.md
internal/function/loc.go

Fixes #982
Language cache was migrated to the new cache API, but this part was
not, and when the cache has not been initialized yet it can lead to
a panic because it does not initialize the cache, only accesses it.

function: use getLanguageCache helper in LOC function
